# -*- coding: utf-8 -*-
"""Merge two shipped model head.h files into one firmware header.

WAKE model (Hallo Lumo, single-head K=5) + CMD model (Licht colors, multi K=3)
coexist in one head.h with prefixed symbols:
  KWS_WAKE_*  -> wake model head weights  (consumed by kws_postprocess_wake)
  KWS_CMD_*   -> command model head weights (consumed by kws_postprocess_cmd)
The two tflite backbones stay separate files in SPIFFS; only the float heads
are compiled in, so this packing is the single compile-time merge point.
"""
import re
import sys

HALLO = r"C:\Users\11745\AppData\Local\Temp\de_models\hallolumo\head.h"
LICHT = r"C:\Users\11745\AppData\Local\Temp\de_models\licht\head.h"
OUT = r"D:\code\voicute\onnx-wakeword\esp32\examples\esp32s3_hmi_devkit\main\head.h"

WAKE_RENAMES = [
    ("KWS_ABS_TEMP", "KWS_WAKE_ABS_TEMP"),
    ("KWS_FC_B", "KWS_WAKE_FC_B"),
    ("KWS_FC_W", "KWS_WAKE_FC_W"),
    ("KWS_PROTO_NORM", "KWS_WAKE_PROTO_NORM"),
]
CMD_RENAMES = [
    ("KWS_HEAD_N", "KWS_CMD_N"),
    ("KWS_HEAD_K", "KWS_CMD_K"),
    ("KWS_ABS_TEMP", "KWS_CMD_ABS_TEMP"),
    ("KWS_FC_B", "KWS_CMD_FC_B"),
    ("KWS_FC_W", "KWS_CMD_FC_W"),
    ("KWS_PROTO_NORM", "KWS_CMD_PROTO_NORM"),
    ("kws_postprocess_multi", "kws_postprocess_cmd"),
]

def rename(text, pairs):
    for a, b in pairs:
        text = re.sub(r"\b%s\b" % a, b, text)
    return text

h = open(HALLO, encoding="utf-8").read()
l = open(LICHT, encoding="utf-8").read()

k_wake = re.search(r"#define KWS_HEAD_K (\d+)", h).group(1)
n_cmd = re.search(r"#define KWS_HEAD_N (\d+)", l).group(1)
k_cmd = re.search(r"#define KWS_HEAD_K (\d+)", l).group(1)
wake_word = re.search(r"#define KWS_WAKE_WORD (u8\"[^\"]+\")", h).group(1)
words = re.findall(r"#define KWS_WAKE_WORD_\d+ (u8\"[^\"]+\")", l)

# Wake weights: from first weight line to EOF (file is weights-only)
wake_w = h[h.index("static const float KWS_ABS_TEMP"):]
wake_w = rename(wake_w, WAKE_RENAMES)

# CMD weights: from first weight line to the function-comment marker
marker = "// Multi-keyword head:"
cmd_w = l[l.index("static const float KWS_ABS_TEMP"):l.index(marker)]
cmd_f = l[l.index(marker):]
cmd_w = rename(cmd_w, CMD_RENAMES)
cmd_f = rename(cmd_f, CMD_RENAMES)

wake_word_lines = "\n".join(
    '#define KWS_CMD_WORD_%d %s' % (i, w) for i, w in enumerate(words))

out = f"""\
// Merged MultiProto head — WAKE ({wake_word[3:-1]}, 1 head K={k_wake})
//                       + CMD (Licht colors, {n_cmd} heads K={k_cmd}).
// Generated by _merge_heads.py from the two shipped model zips; do not edit
// by hand. The tflite backbones stay separate in SPIFFS — only these float
// heads are compiled in (same scheme as the single-model firmware).
#pragma once
#include <math.h>
#include <stdint.h>
// lang: de
#define KWS_WAKE_LANG "de"
#define KWS_MEL_TIME 150
#define KWS_N_MELS 32
#define KWS_TIME_DIM 1
#define KWS_SAMPLE_RATE 16000
#define KWS_MEL_HOP 160
#define KWS_MEL_NFFT 512
#define KWS_HEAD_D 256
#define KWS_WAKE_K {k_wake}
#define KWS_CMD_N {n_cmd}
#define KWS_CMD_K {k_cmd}
{wake_word_lines}

// ---- WAKE model head ({wake_word[3:-1]}) ----
{wake_w}
// ---- CMD model head (Licht colors) ----
{cmd_w}
// Wake head: single MultiProto head, sigmoid over cosine logits.
static inline float kws_postprocess_wake(const int8_t *out_i8, float out_scale,
                                         int out_zero) {{
    float feat[KWS_HEAD_D]; float norm = 0.0f;
    for (int i = 0; i < KWS_HEAD_D; i++) {{
        feat[i] = ((float)out_i8[i] - (float)out_zero) * out_scale;
        norm += feat[i] * feat[i];
    }}
    norm = sqrtf(norm) + 1e-12f;
    for (int i = 0; i < KWS_HEAD_D; i++) feat[i] /= norm;
    float logit = KWS_WAKE_FC_B;
    for (int k = 0; k < KWS_WAKE_K; k++) {{
        float cos = 0.0f;
        for (int i = 0; i < KWS_HEAD_D; i++) cos += feat[i] * KWS_WAKE_PROTO_NORM[k][i];
        logit += KWS_WAKE_FC_W[k] * (cos / KWS_WAKE_ABS_TEMP);
    }}
    return 1.0f / (1.0f + expf(-logit));
}}

{cmd_f}"""

open(OUT, "w", encoding="utf-8", newline="\n").write(out)
print("wrote %s (%d bytes), wake K=%s, cmd N=%s K=%s, words=%s" %
      (OUT, len(out.encode("utf-8")), k_wake, n_cmd, k_cmd,
       [w[3:-1] for w in words]))
